### ISSUE TITLE
Teamerweiterung

### ISSUE THREAD

**Issue by FabianAhammer** [htl-leonding/2018-leonie#11]
Neue 3. Klasse Doku reworken lassen

**Comment by stefnotch** [comment]
Team Invitation Sample Text

> Hallo! Ich bin Stefan Brandmair aus der 5BHIF und kümmere mich um das meiste Leonie 3D Zeugs. Weiteres bin ich derzeit der Team-Leiter. :wave:
Hier ist ein Discord Invite Link zum Leonie-Team Discord Channel. LINK
> Hier ist meine Telefonnummer, damit du mich auf Telegram erreichen kannst wenn wieder mal etwas bei der Leonie nicht funktioniert und Prof. Stuetz ein bisschen einen Druck macht: `+43 681 10594459` 
> Als erstes wuerde ich ein paar Sachen von dir brauchen:
> - Name
> - Klasse
> - GitHub Profil/Benutzername

**Comment by stefnotch** [comment]
- https://github.com/donnabauerc
