### ISSUE TITLE
Add new team members to Leonie Repos

### ISSUE THREAD

**Issue by stefnotch** [htl-leonding/2018-leonie#13]
- [Christian Donnabauer](https://github.com/donnabauerc)
- [Juliana Naderer](https://github.com/julinad)
- [Schirin Turko](https://github.com/schirinturko)
- [Eva Hildenbrand](https://github.com/evahildenbrand)
- [Maria Milic](https://github.com/milicmaria)

need to be added to every single Leonie repository, even the deprecated ones.

**Comment by FabianPrieschl** [comment]
Done

**Comment by stefnotch** [comment]
@htl-leonding Please add the new team members to this repository

**Comment by FabianAhammer** [comment]
- [x] Added to leonie-web
